name: Continuous Integration
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:

  continuous-integration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: auth
        ports:
          - 5432:5432
        options: --name postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Install goose migration
      run: go install github.com/pressly/goose/v3/cmd/goose@latest

    - name: Verify dependencies
      run: go mod verify

    - name: Run database migration
      run: make migration-up

    - name: Run go build
      run: make build

    - name: Run go vet
      run: make vet

    - name: Run staticcheck
      run: make static-check

    - name: Run golint
      run: make lint

    - name: Run tests
      run: make test